---
title: Homage to James Lovelock
author: Walt Ludwick
date: '2019-07-14'
slug: homage-to-james-lovelock
categories:
  - Log
tags:
  - 2pub
description: ''
thumbnail: ''
---
#### _On the occasion of [his 100th birthday](https://www.lovelockcentenary.info/), what to do?_ <br>
<!-- image: taking the pi55 -->

Funny: i had just been thinking of the man, when YouTube's recommendation engine (whose advice i only take while making breakfast, as a rule) threw me this selection- [James Lovelock CCLS2019](https://www.youtube.com/watch?v=38FEJ5A2TTI&t=923s) -from the Cambridge Climate Lecture Series.  Turned out to be a discussion _about_ JL and his theories, with the great man only present via 3 short video segments, so for much of the rest, i paid only partial attention. But in the end, when they threw up a slide announcing this [James Lovelock Centenary event](https://www.lovelockcentenary.info/) -a 3-day confab at Exeter Uni, with Dr. Jim most certainly in attendance- i was sorely tempted to book myself in, straight away... All thought of my carbon footprint gone out the window, for a moment. (Ironic, eh?)

See: _"i was gaia'd"_, as [Stephan Harding](https://www.schumachercollege.org.uk/about/stephan-harding) nicely put it, long before i even had a word for it... But when i stumbled upon Gaia Theory (or Gaia Hypothesis, as "The Scientific Establishment" still called it back then), it explained so many things from my own experience -it's what my life as a ReFarmer is all about, in fact!- it became from that moment my personal favorite answer to the Edge Question: "What do you believe is true, even though you cannot prove it?" 
<p>

Well... Times have changed, and though we certainly

####

gaia 2.0 (tim lenton/ bruno latour): what does it mean?
shift from soft gaia to hard gaia: JL always demurred, but now we must
see his articles
Gaia 2.0 | Science
https://science.sciencemag.org/content/361/6407/1066
Famous theory of the living Earth upgraded to 'Gaia 2.0' -- ScienceDaily
https://www.sciencedaily.com/releases/2018/09/180913142050.htm
relevance: my work on indicators (leading and lagging, dir&proxy)
indicators alone won't make any diff, necessarily
are a precondition: necessary but insufficient in and of itself
we are as gods, and we MUST get good at it
YNH:  B*C*D=AHH
understand -> predict -> control
moreover
it's political (see Collective Impact)
even more: it's personal
what i would be doing in my daily routine, over those 3 days
guinea pig B
the biochar experiment -not!
instead, a humble experiment
tied into the rest (closing open loops, making those I/O connections)
wormery for the soft OM (fire for the hard)
doing the right thing with water (canonical sources)
humanure: The Humanure Handbook - Instructional Manual
https://humanurehandbook.com/manual.html
greywater: link to Art Ludwig
rainwater: Brad Lancaster
personal significance
my father's thing about destroying nature
lesson of porcupine (and mine of the frogs, the deer)
take care of gun, it will take care of you
my experience of being gaia'd
it was a feeling, an intuition -a certainty
my merton prayer (it goes beyond)
complacency vs complicity
/we= only animal that shits its nest
living & learning closer to nature means bioMimicry
and gaia principle is fundamental
related thoughts
if you don't love it, you won't care for it
i like the gaia peope (lovelock & margulis, others)
stephan's "animate earth", walking around Martin Crawford's FF, the butterfly
my friend Carmen; my talk w/ satishKumar: native americans knew:
austerity does not sell!
nature connection xperience
when i was young, i would have gone (ironic!)
i believed more then in my ability to Change The World
now: i think my place is puttering about my garden, muttering incantations....
closing: we must tend our gardens
"a man gets tied up to the ground...
"he gives the world its saddest sound" -not!
Living & Learning Closer to Nature
it's the most joyful way to live
AND your best chance at redemption/ salvation (if you believe)
your most ethical/ enlightened choice (if you don't necessarily)
