---
title: Fruticulture Toughlove
author: Walt Ludwick
date: '2019-08-11'
categories:
  - HowTo
tags:
  - AgroForestry
slug: fruticulture-toughlove
---
Tree-Huggers that we are, it's always hard to cut living wood, but -as [Nick Lowe put it tunefully](https://www.youtube.com/watch?v=b0l3QWUXVho), if a bit too cutesilly- "You've got to be cruel to be kind," if you hope to enjoy a good harvest.  Long story to tell about this, complete with annotated pictures that i've uploaded to this photo album at Imgur...

<blockquote class="imgur-embed-pub" lang="en" data-id="a/YLbWV0p"><a href="//imgur.com/a/YLbWV0p">In the Land of Fruits &amp; Nuts</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

... but for the purposes of this blog, i'll be brief.  When it comes to big old trees like the almond pictured above, that's another topic for another day; anyway, it's harvest time now for almonds, carobs & figs, and fruiting trees are only pruned after the harvest (still ongoing).  As for baby trees -i.e. those ~250 soft fruit trees we planted last winter, plus those ~100 carob trees planted in November of 2017 that were just grafted in spring of this year- they were sorely in need of some formative pruning, so we've been busy with that the last few days.  Blessed with a visit from expert fruticulturists Catarina Joaquim & Carlos Simões, we learned some valuable lessons, which i would summarise as follows:

### getting rid of suckers:
- Anything below the graft must go -Pronto!
  - Reason why: Root = Mother; Wild shoots = Children; Graft = Bastard.  Mother will starve the latter for sake of former -always! (i.e. you're stuck with this maintenance task for life)
- Caution: don't prune during extreme heat wave, or freezing temp... And irrigate as soon as possible after. <br>


### getting rid of unwanted branches:
- If they are green (i.e. this year's growth), can be pruned without negative consequence
- If they have turned woody: pinch off the end, prune after leaf fall

### cutting technique
- Cut as close to trunk as possible
- With cutting edge of pruning shears to the inside...
- Cut down and away from tree

### reforming branches that are growing too vertical? two ways:
- Insert a brace
- Tie off to itself, or to a weight <br>
Timing?  _As soon as possible!_

See: as with music, comedy, sex (all the good things in life!), the magic is in the timing... And, like all living things, fruit trees have their own sense of time.  Though we may look to the calendar as a guide, every season is a different story, each plant responds in its own way, and we have to be sensitive to its needs as and when expressed. Above all: don't delay, when the need for intervention is made manifest, act decisively; remember, "A stitch in time saves nine," even if it hurts a bit -you can tell her (as Nick does) it "Means that i love you, bay-beee!" :smiley:

{{% youtube b0l3QWUXVho %}}
