---
title: 'ABOUT: rf1,Dev'
author: Walt Ludwick
date: '2019-07-10'
slug: about-rf1-dev
categories:
  - workflow
tags:
  - (R)MD
description: ''
thumbnail: ''
---
At this point i have to say: i'm feeling good right now, because it seems like i have finally found a way to cultivate the habit of writing in a form that works for me personally, can support my work on the farm, and can (eventually) reach a wider audience to achieve a (eventually) growing measure of collective impact... And the foundation of this approach is right here [rf1,Dev blog](http://127.0.0.1:4321/). Let's ouline a few key points, essential to understanding how this works.

## Key Points:

- All writing for posterity (i.e. a future audience, including "my future self" as much as anyone) begins here -with parameters expressed in TOML frontmatter.
- By default, all writings here (under security by the relative obscurity of my computer) remain here, unless tagged 2PUB.
- 2PUB-tagged items are the focus of my own editorial process, based on [Merlin Mann's advice](/post/merlin-mann-s-advice/index.html).
- Though RStudio is the best IDE for what i do, it's not the best text editor -so for that, i work in Atom, which affords power tools (e.g. code/header folding), and plays nicely w/ RStudio (i.e. edits saved on either side show up immediately on the other).
- Following publication of a 2PUB-tagged item to ReFarmer.net ( via port-over to blog_rf1/ push), must [delete it](/post/deleting-content/index.html) from blog_rf1,Dev.
- Backup of ALL content should be ensured (using Dropbox, probably, pending satisfaction of concerns about both privacy and capacity; check it out).

NB: See the relative link in 3rd bullet point above? it is long, even though it using the slug... But if i can remember that public/ is the default location of relative links, then perhaps i can get it learn this Hugo filesystem easily enough that this is not a problem.  time will tell!

Cool thing (one of many) is: by keeping this local site (127.0.0.1:4321) open in my browser, i can have a live view on how content is being rendered, updated every time i save the file in RStudio -don't even hove to refresh the browser!- so i needn't use the "view" function in RStudio, and can instead keep that panel of IDE open to the file browser.
