---
title: Merlin Mann’s advice
author: Walt Ludwick
date: '2019-07-02'
slug: merlin-mann-s-advice
categories:
  - TechHow
tags:
  - WL
  - private
description: ''
thumbnail: ''
---

Best advice i ever heard for wanna be bloggers came from a guy whose stuff i used to lap up eagerly, every morsel he ever released, until he went silent quite some time ago (he's still alive -i've checked- i think he just got tired of his own schtick).  The man is Merlin Mann, and this came from a presentation he did entitled "How to Blog" -which video i did see, a good few years ago; can't find it now, but i did find his SlideShare deck -notes from which are cribbed below, because i don't wanna lose this stuff, it's important.

PS: i did manage to find a podcast he did with Jon Gruber -tho i don't have time to hear it now- in which he reduced his process down to a 2-factor equation: Focus * Voice = Blogging success.  (sounds like Intensity w/ Vision, or Discipline + Passion -2 more big ideas from the past ;-)

## The 9 Keys:

1. Obsession!
2. Daily!
3. Explain it!
4. One person!
5. Respect!
6. Edit it!
7. No cheese!
8. No dick!
9. Better!

In summary:
Find your passion, Every day, Explain it to one person you respect. 
Edit everything, Skip shortcuts, and Try not to be a dick. 
Get better.

## QUOTE: Merlin to JohnGruber at SXSW Interactive, 2009
“Topic times voice. Or, if you’re a little bit more of a maverick, obsession times voice. So what does that mean? I think all of the best nonfiction that has ever been made comes from the result of someone who can’t stop thinking about a certain topic — a very specific aspect of a certain topic in some cases. And second, they got really good at figuring out what they had to say about it.”
`Gruber objects only to say: it's more broadly applicable (not just nonFiction)`
In other words:  Focus * Voice = Blogging success.  (sounds like Intensity w/ Vision, or Discipline + Passion -2 more big ideas from the past ;-)

## Things not to sweat (yet):

- SEO
- Traffic
- Ads
- Design
- Fame

In the time you set aside every day to work your ass off, do NOT get sucked into the morass of thinking about ANY of those things.  Instead, keep your focus on the story.

## 3 Focus Questions:

- What do i really want to talk about?
- Why?  Why does that matter?
- For whom? Who else would care about this?

Clear?  Then go do the shit out of that thing!  
